// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SearchOptimizationBE.Data;

#nullable disable

namespace SearchOptimizationBE.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427114810_InitialLegacySchema")]
    partial class InitialLegacySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SearchOptimizationBE.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("FileSizeKb")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("UploadedAt");

                    b.HasIndex("UploadedById");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("SearchOptimizationBE.Models.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sözleşme"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Teklif"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fatura"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Diğer"
                        });
                });

            modelBuilder.Entity("SearchOptimizationBE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Hukuk",
                            FullName = "Ayşe Yılmaz"
                        },
                        new
                        {
                            Id = 2,
                            Department = "Satınalma",
                            FullName = "Mehmet Demir"
                        },
                        new
                        {
                            Id = 3,
                            Department = "Finans",
                            FullName = "Fatma Kaya"
                        },
                        new
                        {
                            Id = 4,
                            Department = "Satış",
                            FullName = "Can Öztürk"
                        },
                        new
                        {
                            Id = 5,
                            Department = "İK",
                            FullName = "Zeynep Aydın"
                        },
                        new
                        {
                            Id = 6,
                            Department = "Operasyon",
                            FullName = "Burak Şahin"
                        },
                        new
                        {
                            Id = 7,
                            Department = "Pazarlama",
                            FullName = "Selin Çelik"
                        },
                        new
                        {
                            Id = 8,
                            Department = "Bilgi Teknolojileri",
                            FullName = "Emre Aslan"
                        });
                });

            modelBuilder.Entity("SearchOptimizationBE.Models.Document", b =>
                {
                    b.HasOne("SearchOptimizationBE.Models.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SearchOptimizationBE.Models.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("UploadedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
